apiVersion: apps/v1
kind: Deployment
metadata:
  name: mensfashion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mxf-app
  template:
    metadata:
      labels:
        app: mxf-app
    spec:
      containers:
        - name: mxf-app
          image: hudyfa/mensfashion
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: EMAIL
              value: hudyfaismail@gmail.com
            - name: PASS
              value: cjxercwuuzjriama
            - name: RAZORPAY_ID_KEY
              value: rzp_test_AGAl3sXv1UmAjD
            - name: RAZORPAY_SECRET_KEY
              value: aXyvxZPVxs0Iu5pWfQLsIjom
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
