name: mensfashion CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: notification
        run: echo "codebase updated"
        shell: bash

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build docker image
      run: docker build -t hudyfa/mensfashion:latest .

    - name: Push docker image to docker hub
      run: docker push hudyfa/mensfashion:latest
